In [192]:
import pandas as pd
import numpy as np
import math
from sklearn.preprocessing import OneHotEncoder

In [193]:
df = pd.read_csv('./train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# Pre-processing

In [194]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [195]:
## Delete Un-necessary Column
df.drop(['PassengerId','Name','Ticket','Cabin'],axis = 1 ,inplace = True)

In [196]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [197]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [198]:
df[df['Age'].isnull() == True]

Survived  Pclass     Sex  Age  SibSp  Parch     Fare Embarked
5           0       3    male  NaN      0      0   8.4583        Q
17          1       2    male  NaN      0      0  13.0000        S
19          1       3  female  NaN      0      0   7.2250        C
26          0       3    male  NaN      0      0   7.2250        C
28          1       3  female  NaN      0      0   7.8792        Q
..        ...     ...     ...  ...    ...    ...      ...      ...
859         0       3    male  NaN      0      0   7.2292        C
863         0       3  female  NaN      8      2  69.5500        S
868         0       3    male  NaN      0      0   9.5000        S
878         0       3    male  NaN      0      0   7.8958        S
888         0       3  female  NaN      1      2  23.4500        S

[177 rows x 8 columns]

In [199]:
df['Age'].fillna(np.mean(df['Age']),inplace=True)

In [200]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [201]:
df[df['Embarked'].isnull()]

Survived  Pclass     Sex   Age  SibSp  Parch  Fare Embarked
61          1       1  female  38.0      0      0  80.0      NaN
829         1       1  female  62.0      0      0  80.0      NaN

In [202]:
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace = True)

In [203]:
df[df['Embarked'].isnull()]

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []

In [204]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [205]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [206]:
df['Sex'] = np.where(df['Sex'] == 'male',0,1)
df['Sex'].value_counts()

0    577
1    314
Name: Sex, dtype: int64

In [207]:
df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [208]:
df['Age'] = df['Age'].apply(lambda x : math.ceil(x))
df['Age'].unique()

array([22, 38, 26, 35, 30, 54,  2, 27, 14,  4, 58, 20, 39, 55, 31, 34, 15,
       28,  8, 19, 40, 66, 42, 21, 18,  3,  7, 49, 29, 65,  5, 11, 45, 17,
       32, 16, 25,  1, 33, 23, 24, 46, 59, 71, 37, 47, 12,  9, 51, 56, 41,
       44, 61, 50, 36, 62, 52, 63, 43, 60, 10, 64, 13, 48, 53, 57, 80, 70,
        6, 74], dtype=int64)

In [209]:
df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [210]:
df['Fare'] = df['Fare'].apply(lambda x: round(x,2)) 

In [211]:
df['Fare'].unique()

array([  7.25,  71.28,   7.92,  53.1 ,   8.05,   8.46,  51.86,  21.07,
        11.13,  30.07,  16.7 ,  26.55,  31.27,   7.85,  16.  ,  29.12,
        13.  ,  18.  ,   7.22,  26.  ,   8.03,  35.5 ,  31.39, 263.  ,
         7.88,   7.9 ,  27.72, 146.52,   7.75,  10.5 ,  82.17,  52.  ,
         7.23,  11.24,   9.47,  21.  ,  41.58,  15.5 ,  21.68,  17.8 ,
        39.69,   7.8 ,  76.73,  61.98,  27.75,  46.9 ,  80.  ,  83.47,
        27.9 ,  15.25,   8.16,   8.66,  73.5 ,  14.45,  56.5 ,   7.65,
        29.  ,  12.47,   9.  ,   9.5 ,   7.79,  47.1 ,  15.85,  34.38,
        61.17,  20.57,  34.65,  63.36,  23.  ,  77.29,   8.65,   7.78,
        24.15,   9.82,  14.46, 247.52,   7.14,  22.36,   6.97,   7.05,
        14.5 ,  15.05,  26.28,   9.22,  79.2 ,   6.75,  11.5 ,  36.75,
        12.53,  66.6 ,   7.31,  61.38,   7.73,  69.55,  16.1 ,  15.75,
        20.52,  55.  ,  25.93,  33.5 ,  30.7 ,  25.47,  28.71,   0.  ,
        39.  ,  22.02,  50.  ,   8.4 ,   6.5 ,  10.46,  18.79,  31.  ,
      

In [212]:
# Encoding Embarked Column
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Embarked']]).toarray()
encoded_df = pd.DataFrame(encoded,columns = encoder.get_feature_names_out())
df = pd.concat([df,encoded_df],axis = 1)
df.drop('Embarked',axis = 1,inplace = True)

In [213]:
df

Survived  Pclass  Sex  Age  SibSp  Parch   Fare  Embarked_C  Embarked_Q  \
0           0       3    0   22      1      0   7.25         0.0         0.0   
1           1       1    1   38      1      0  71.28         1.0         0.0   
2           1       3    1   26      0      0   7.92         0.0         0.0   
3           1       1    1   35      1      0  53.10         0.0         0.0   
4           0       3    0   35      0      0   8.05         0.0         0.0   
..        ...     ...  ...  ...    ...    ...    ...         ...         ...   
886         0       2    0   27      0      0  13.00         0.0         0.0   
887         1       1    1   19      0      0  30.00         0.0         0.0   
888         0       3    1   30      1      2  23.45         0.0         0.0   
889         1       1    0   26      0      0  30.00         1.0         0.0   
890         0       3    0   32      0      0   7.75         0.0         1.0   

     Embarked_S  
0           1.0  
1           0.0  
2           1.0  
3           1.0  
4           1.0  
..          ...  
886         1.0  
887         1.0  
888         1.0  
889         0.0  
890         0.0  

[891 rows x 10 columns]

#### Divide Independent and Dependent Variable

In [214]:
X = df.drop('Survived',axis = 1)
y = df['Survived']

#### Train Test Split

In [215]:
from sklearn.model_selection import train_test_split

In [216]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 40,test_size = 0.2)

In [217]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 9), (179, 9), (712,), (179,))

In [218]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
import warnings
warnings.filterwarnings('ignore')

#### intializing Cross Validation

In [219]:
cv = KFold(n_splits= 5)
cv

KFold(n_splits=5, random_state=None, shuffle=False)

#### HyperParameter Tunnig

In [220]:
parameter = {'penalty':['l1','l2','elasticnet'],'C' : [1,5,10,15,20]}
clf = GridSearchCV(LogisticRegression(),param_grid = parameter,cv = cv)

In [221]:
clf.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [1, 5, 10, 15, 20],
                         'penalty': ['l1', 'l2', 'elasticnet']})

In [222]:
clf.best_params_

{'C': 15, 'penalty': 'l2'}

In [223]:
## It is the mean of score of cross validation
clf.best_score_

0.792140254112085

In [224]:
y_pred = clf.predict(X_test)
y_pred

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1], dtype=int64)

In [225]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[87 16]
 [17 59]]
0.8156424581005587
              precision    recall  f1-score   support

           0       0.84      0.84      0.84       103
           1       0.79      0.78      0.78        76

    accuracy                           0.82       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179



# Test Data

In [233]:
df = pd.read_csv('./test.csv')
df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

## Do the same preprocess as you done on Traning Data

In [234]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [235]:
df.drop(['PassengerId','Name','Ticket','Cabin'],axis = 1 ,inplace = True)

In [236]:
df.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [237]:
df['Age'].fillna(np.mean(df['Age']),inplace=True)

In [238]:
df.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [239]:
df['Fare'].fillna(np.mean(df['Fare']),inplace = True)

In [240]:
df.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [241]:
df['Sex'] = np.where(df['Sex'] == 'male',0,1)
df['Sex'].value_counts()

0    266
1    152
Name: Sex, dtype: int64

In [247]:
df['Age'] = df['Age'].apply(lambda x : math.ceil(x))
df['Age'].unique()

array([35, 47, 62, 27, 22, 14, 30, 26, 18, 21, 31, 46, 23, 63, 24, 45, 55,
        9, 48, 50, 41, 33, 19, 25, 39, 60, 36, 20, 28, 10, 17, 32, 13, 29,
        6, 67, 49,  2, 76, 43, 16,  1, 12, 42, 53, 40, 61,  7, 15, 54, 64,
       37, 34,  8, 38, 57, 58, 59, 44,  5, 51,  3], dtype=int64)

In [242]:
df['Fare'] = df['Fare'].apply(lambda x: round(x,2)) 

In [243]:
# Encoding Embarked Column
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Embarked']]).toarray()
encoded_df = pd.DataFrame(encoded,columns = encoder.get_feature_names_out())
df = pd.concat([df,encoded_df],axis = 1)
df.drop('Embarked',axis = 1,inplace = True)

In [250]:
X_test = df.copy()
X_test

Pclass  Sex  Age  SibSp  Parch    Fare  Embarked_C  Embarked_Q  \
0         3    0   35      0      0    7.83         0.0         1.0   
1         3    1   47      1      0    7.00         0.0         0.0   
2         2    0   62      0      0    9.69         0.0         1.0   
3         3    0   27      0      0    8.66         0.0         0.0   
4         3    1   22      1      1   12.29         0.0         0.0   
..      ...  ...  ...    ...    ...     ...         ...         ...   
413       3    0   31      0      0    8.05         0.0         0.0   
414       1    1   39      0      0  108.90         1.0         0.0   
415       3    0   39      0      0    7.25         0.0         0.0   
416       3    0   31      0      0    8.05         0.0         0.0   
417       3    0   31      1      1   22.36         1.0         0.0   

     Embarked_S  
0           0.0  
1           1.0  
2           0.0  
3           1.0  
4           1.0  
..          ...  
413         1.0  
414         0.0  
415         1.0  
416         1.0  
417         0.0  

[418 rows x 9 columns]

# Predict 

In [251]:
y_pred = clf.predict(X_test)

In [252]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [253]:
## Put this data into submission File

In [255]:
submission = pd.read_csv('./gender_submission.csv')
submission

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [256]:
submission['Survived'] = y_pred

In [258]:
submission

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [262]:
submission.to_csv('submission.csv',index=False)

In [261]:
clf.predict_proba(X_test)

array([[0.89225268, 0.10774732],
       [0.66905397, 0.33094603],
       [0.89275789, 0.10724211],
       [0.90106768, 0.09893232],
       [0.43815654, 0.56184346],
       [0.84198036, 0.15801964],
       [0.33510427, 0.66489573],
       [0.80272209, 0.19727791],
       [0.19339736, 0.80660264],
       [0.9234624 , 0.0765376 ],
       [0.91482299, 0.08517701],
       [0.68533534, 0.31466466],
       [0.07653132, 0.92346868],
       [0.94538604, 0.05461396],
       [0.18180551, 0.81819449],
       [0.11683241, 0.88316759],
       [0.73224279, 0.26775721],
       [0.78389923, 0.21610077],
       [0.46982158, 0.53017842],
       [0.42203327, 0.57796673],
       [0.67819828, 0.32180172],
       [0.82396617, 0.17603383],
       [0.08075015, 0.91924985],
       [0.30114609, 0.69885391],
       [0.13377225, 0.86622775],
       [0.9683797 , 0.0316203 ],
       [0.03250304, 0.96749696],
       [0.79754627, 0.20245373],
       [0.63944242, 0.36055758],
       [0.90286791, 0.09713209],
       [0.